#!/bin/bash

: ${DOCKERDNS_FILE:="/etc/dnsmasq.d/docker"}
: ${DOCKERDNS_SUFFIX:=".docker.local"}

echo -n '' > $DOCKERDNS_FILE || exit

for CONTAINER in `docker ps -q`
do
	NAME=`docker inspect -f "{{.Name}}" $CONTAINER | sed -e 's/^\/*//'`
	ADDRESS=`docker inspect -f "{{.NetworkSettings.IPAddress}}" $CONTAINER`
	echo "add DNS record: $NAME$DOCKERDNS_SUFFIX => $ADDRESS"
	echo "address=/$NAME$DOCKERDNS_SUFFIX/$ADDRESS" >> $DOCKERDNS_FILE
done

echo "$DOCKERDNS_FILE updated."

service dnsmasq restart
